modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/davidjjung/sagebrush/issues"
license = "MIT License"

[[mixins]]
config = "sage_brush.mixins.json"

[[mods]]
modId = "sage_brush"
version = "${mod_version}"
logoFile = "logo.png"
itemIcon = "minecraft:brush"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = "DavigJ"
displayURL = "https://modrinth.com/mod/sage-brush"
displayName = "Sage Brush"
description = '''Wisens up brushes a bit.'''

[[dependencies.sage_brush]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sage_brush]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sage_brush]]
modId = "blueprint"
type = "required"
versionRange = "[${blueprint},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sage_brush]]
modId = "mixed_litter"
type = "optional"
versionRange = "[1.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sage_brush]]
modId = "nomansland"
type = "optional"
versionRange = "[1.4.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sage_brush]]
modId = "environmental"
type = "optional"
versionRange = "[5.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sage_brush]]
modId = "naturalist"
type = "optional"
versionRange = "[1.0.2,)"
ordering = "AFTER"
side = "BOTH"